name: Deploy to Dev Environment

on: workflow_dispatch # yamllint disable-line rule:truthy
#  workflow_run:
#    workflows: ["Build & Push Images to AWS ECR for Dev / Staging branches"]
#    types:
#      - completed

jobs:
  deploy-to-dev:
    name: (Dev) Deploy indexer
    uses: ./.github/workflows/reusable-deploy-to-env.yml
    with:
      ENVIRONMENT: dev
    secrets: inherit

  deploy-to-dev2:
    name: (Dev2) Deploy indexer
    uses: ./.github/workflows/reusable-deploy-to-env.yml
    with:
      ENVIRONMENT: dev2
    secrets: inherit

  deploy-to-dev3:
    name: (Dev3) Deploy indexer
    uses: ./.github/workflows/reusable-deploy-to-env.yml
    with:
      ENVIRONMENT: dev3
    secrets: inherit

  deploy-to-dev4:
    name: (Dev4) Deploy indexer
    uses: ./.github/workflows/reusable-deploy-to-env.yml
    with:
      ENVIRONMENT: dev4
    secrets: inherit

  deploy-to-dev5:
    name: (Dev5) Deploy indexer
    uses: ./.github/workflows/reusable-deploy-to-env.yml
    with:
      ENVIRONMENT: dev5
    secrets: inherit
